# Generated by Django 5.1.3 on 2024-11-26 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('postal_code', models.IntegerField()),
                ('province', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=9)),
                ('mobile_phone', models.CharField(blank=True, max_length=18, null=True)),
                ('birth_date', models.DateField(blank=True, default='2000-01-01', null=True)),
                ('registration_date', models.DateTimeField(blank=True, default='2000-01-01', null=True)),
                ('last_access', models.DateTimeField(blank=True, default='2000-01-01', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('native_languages', models.CharField(blank=True, max_length=20, null=True)),
                ('education', models.CharField(blank=True, max_length=40, null=True)),
                ('degree', models.CharField(blank=True, max_length=50, null=True)),
                ('employment_status', models.CharField(blank=True, max_length=20, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('softwares', models.CharField(blank=True, max_length=250, null=True)),
                ('translator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_language', models.CharField(choices=[('Alemán', 'Alemán'), ('Árabe', 'Árabe'), ('Bosnio', 'Bosnio'), ('Búlgaro', 'Búlgaro'), ('Catalán', 'Catalán'), ('Checo', 'Checo'), ('Chino', 'Chino'), ('Coreano', 'Coreano'), ('Croata', 'Croata'), ('Danés', 'Danés'), ('Eslovaco', 'Eslovaco'), ('Esloveno', 'Esloveno'), ('Español', 'Español'), ('Español (MX)', 'Español (MX)'), ('Euskera', 'Euskera'), ('Filipino', 'Filipino'), ('Finés', 'Finés'), ('Francés', 'Francés'), ('Francés (CA)', 'Francés (CA)'), ('Gallego', 'Gallego'), ('Georgiano', 'Georgiano'), ('Griego', 'Griego'), ('Hebreo', 'Hebreo'), ('Hindi', 'Hindi'), ('Holandés', 'Holandés'), ('Húngaro', 'Húngaro'), ('Inglés', 'Inglés'), ('Islandés', 'Islandés'), ('Italiano', 'Italiano'), ('Japonés', 'Japonés'), ('Lituano', 'Lituano'), ('Noruego', 'Noruego'), ('Polaco', 'Polaco'), ('Portugués (BR)', 'Portugués (BR)'), ('Portugués (PT)', 'Portugués (PT)'), ('Rumano', 'Rumano'), ('Ruso', 'Ruso'), ('Serbio', 'Serbio'), ('Singalés', 'Singalés'), ('Sueco', 'Sueco'), ('Tailandés', 'Tailandés'), ('Turco', 'Turco'), ('Ucraniano', 'Ucraniano'), ('Urdu', 'Urdu'), ('Valenciano', 'Valenciano'), ('Vietnamita', 'Vietnamita')], max_length=50)),
                ('target_language', models.CharField(choices=[('Alemán', 'Alemán'), ('Árabe', 'Árabe'), ('Bosnio', 'Bosnio'), ('Búlgaro', 'Búlgaro'), ('Catalán', 'Catalán'), ('Checo', 'Checo'), ('Chino', 'Chino'), ('Coreano', 'Coreano'), ('Croata', 'Croata'), ('Danés', 'Danés'), ('Eslovaco', 'Eslovaco'), ('Esloveno', 'Esloveno'), ('Español', 'Español'), ('Español (MX)', 'Español (MX)'), ('Euskera', 'Euskera'), ('Filipino', 'Filipino'), ('Finés', 'Finés'), ('Francés', 'Francés'), ('Francés (CA)', 'Francés (CA)'), ('Gallego', 'Gallego'), ('Georgiano', 'Georgiano'), ('Griego', 'Griego'), ('Hebreo', 'Hebreo'), ('Hindi', 'Hindi'), ('Holandés', 'Holandés'), ('Húngaro', 'Húngaro'), ('Inglés', 'Inglés'), ('Islandés', 'Islandés'), ('Italiano', 'Italiano'), ('Japonés', 'Japonés'), ('Lituano', 'Lituano'), ('Noruego', 'Noruego'), ('Polaco', 'Polaco'), ('Portugués (BR)', 'Portugués (BR)'), ('Portugués (PT)', 'Portugués (PT)'), ('Rumano', 'Rumano'), ('Ruso', 'Ruso'), ('Serbio', 'Serbio'), ('Singalés', 'Singalés'), ('Sueco', 'Sueco'), ('Tailandés', 'Tailandés'), ('Turco', 'Turco'), ('Ucraniano', 'Ucraniano'), ('Urdu', 'Urdu'), ('Valenciano', 'Valenciano'), ('Vietnamita', 'Vietnamita')], max_length=50)),
                ('services', models.CharField(blank=True, max_length=200)),
                ('texts', models.CharField(blank=True, max_length=100)),
                ('rate_per_word', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('certified_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('rate_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('translator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_combinations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('translator', 'source_language', 'target_language', 'services')},
            },
        ),
    ]
