# Generated by Django 5.1.3 on 2024-11-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0008_alter_languagecombination_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagecombination',
            name='services',
            field=models.TextField(blank=True, max_length=200, verbose_name='Servicios'),
        ),
        migrations.AlterField(
            model_name='languagecombination',
            name='text_types',
            field=models.TextField(blank=True, max_length=100, verbose_name='Textos'),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='native_languages',
            field=models.TextField(blank=True, max_length=20, verbose_name='Lenguas Nativas'),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='softwares',
            field=models.TextField(blank=True, default='', max_length=250, verbose_name='Softwares'),
        ),
    ]
