# Generated by Django 5.1.3 on 2024-12-02 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0012_alter_languagecombination_price_per_hour_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curriculum',
            new_name='Files',
        ),
    ]
