# Generated by Django 5.1.3 on 2024-11-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0007_alter_professionalprofile_native_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagecombination',
            name='services',
            field=models.TextField(blank=True, choices=[('Traducción', 'Traducción'), ('Traducción jurada', 'Traducción jurada'), ('Revisión', 'Revisión'), ('Interpretación consecutiva', 'Interpretación consecutiva'), ('Interpretación simultánea', 'Interpretación simultánea'), ('Interpretación susurrada', 'Interpretación susurrada'), ('Interpretación telefónica', 'Interpretación telefónica'), ('Transcripción', 'Transcripción'), ('Locución', 'Locución'), ('Doblaje', 'Doblaje'), ('Maquetación', 'Maquetación')], max_length=200, verbose_name='Servicios'),
        ),
        migrations.AlterField(
            model_name='languagecombination',
            name='text_types',
            field=models.TextField(blank=True, choices=[('Científico', 'Científico'), ('Técnico', 'Técnico'), ('Económico', 'Económico'), ('Financiero', 'Financiero'), ('Informático', 'Informático'), ('Jurídico', 'Jurídico'), ('Legal', 'Legal'), ('Literario', 'Literario'), ('Marketing', 'Marketing'), ('Médico', 'Médico'), ('Cultural', 'Cultural'), ('Gastronómico', 'Gastronómico'), ('Comercial', 'Comercial'), ('Empresarial', 'Empresarial'), ('Inmobiliario', 'Inmobiliario'), ('Cosmético', 'Cosmético'), ('Vitivinícola', 'Vitivinícola'), ('Patentes', 'Patentes')], max_length=100, verbose_name='Textos'),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='native_languages',
            field=models.TextField(blank=True, choices=[('Alemán', 'Alemán'), ('Árabe', 'Árabe'), ('Bosnio', 'Bosnio'), ('Búlgaro', 'Búlgaro'), ('Catalán', 'Catalán'), ('Checo', 'Checo'), ('Chino', 'Chino'), ('Coreano', 'Coreano'), ('Croata', 'Croata'), ('Danés', 'Danés'), ('Eslovaco', 'Eslovaco'), ('Esloveno', 'Esloveno'), ('Español', 'Español'), ('Español (MX)', 'Español (MX)'), ('Euskera', 'Euskera'), ('Filipino', 'Filipino'), ('Finés', 'Finés'), ('Francés', 'Francés'), ('Francés (CA)', 'Francés (CA)'), ('Gallego', 'Gallego'), ('Georgiano', 'Georgiano'), ('Griego', 'Griego'), ('Hebreo', 'Hebreo'), ('Hindi', 'Hindi'), ('Holandés', 'Holandés'), ('Húngaro', 'Húngaro'), ('Inglés', 'Inglés'), ('Islandés', 'Islandés'), ('Italiano', 'Italiano'), ('Japonés', 'Japonés'), ('Lituano', 'Lituano'), ('Noruego', 'Noruego'), ('Polaco', 'Polaco'), ('Portugués (BR)', 'Portugués (BR)'), ('Portugués (PT)', 'Portugués (PT)'), ('Rumano', 'Rumano'), ('Ruso', 'Ruso'), ('Serbio', 'Serbio'), ('Singalés', 'Singalés'), ('Sueco', 'Sueco'), ('Tailandés', 'Tailandés'), ('Turco', 'Turco'), ('Ucraniano', 'Ucraniano'), ('Urdu', 'Urdu'), ('Valenciano', 'Valenciano'), ('Vietnamita', 'Vietnamita')], default='', max_length=20, verbose_name='Lenguas Nativas'),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='softwares',
            field=models.TextField(blank=True, choices=[('Adobe Indesign', 'Adobe Indesign'), ('SDL TRADOS Studio', 'SDL TRADOS Studio'), ('Wordfast (cat-tool)', 'Wordfast (cat-tool)'), ('Adobe Illustrator', 'Adobe Illustrator'), ('Adobe Photoshop', 'Adobe Photoshop'), ('AutoCAD', 'AutoCAD'), ('FrameMaker', 'FrameMaker'), ('Microsoft Excel', 'Microsoft Excel'), ('Passolo (cat-tool)', 'Passolo (cat-tool)'), ('Microsoft Powerpoint', 'Microsoft Powerpoint'), ('MemoQ', 'MemoQ')], default='', max_length=250, verbose_name='Softwares'),
        ),
    ]
