# Generated by Django 5.1.4 on 2025-01-28 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0022_alter_languagecombination_translator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagecombination',
            name='translator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_combination', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='translator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
