# Generated by Django 5.1.3 on 2024-11-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0003_rename_rate_per_hour_languagecombination_price_per_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagecombination',
            name='services',
            field=models.CharField(blank=True, choices=[('Traducción', 'Traducción'), ('Traducción jurada', 'Traducción jurada'), ('Revisión', 'Revisión'), ('Interpretación consecutiva', 'Interpretación consecutiva'), ('Interpretación simultánea', 'Interpretación simultánea'), ('Interpretación susurrada', 'Interpretación susurrada'), ('Interpretación telefónica', 'Interpretación telefónica'), ('Transcripción', 'Transcripción'), ('Locución', 'Locución'), ('Doblaje', 'Doblaje'), ('Maquetación', 'Maquetación')], max_length=200, verbose_name='Servicios'),
        ),
        migrations.AlterField(
            model_name='languagecombination',
            name='text_types',
            field=models.CharField(blank=True, choices=[('Científico', 'Científico'), ('Técnico', 'Técnico'), ('Económico', 'Económico'), ('Financiero', 'Financiero'), ('Informático', 'Informático'), ('Jurídico', 'Jurídico'), ('Legal', 'Legal'), ('Literario', 'Literario'), ('Marketing', 'Marketing'), ('Médico', 'Médico'), ('Cultural', 'Cultural'), ('Gastronómico', 'Gastronómico'), ('Comercial', 'Comercial'), ('Empresarial', 'Empresarial'), ('Inmobiliario', 'Inmobiliario'), ('Cosmético', 'Cosmético'), ('Vitivinícola', 'Vitivinícola'), ('Patentes', 'Patentes')], max_length=100, verbose_name='Textos'),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='education',
            field=models.CharField(blank=True, choices=[('ESO', 'ESO'), ('Bachillerato', 'Bachillerato'), ('FPI/Ciclo Formativo de Grado Medio', 'FPI/Ciclo Formativo de Grado Medio'), ('FPII/Ciclo Formativo de Grado Superior', 'FPII/Ciclo Formativo de Grado Superior'), ('Diplomatura', 'Diplomatura'), ('Licenciatura', 'Licenciatura'), ('Doctorado', 'Doctorado'), ('Cursos de Postgrado', 'Cursos de Postgrado'), ('Master', 'Master'), ('Otros', 'Otros')], max_length=40, null=True, verbose_name='Educación'),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('Autonomo', 'Autonomo'), ('Traductor ocasional', 'Traductor ocasional'), ('Estudiante', 'Estudiante'), ('Agencia', 'Agencia')], max_length=20, null=True, verbose_name='Situación Laboral'),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='experience',
            field=models.IntegerField(blank=True, choices=[('Sin experiencia', 'Sin experiencia'), ('Menos de 6 meses', 'Menos de 6 meses'), ('6 meses - 1 año', '6 meses - 1 año'), ('1 - 2 años', '1 - 2 años'), ('2 - 5 años', '2 - 5 años'), ('5 - 10 años', '5 - 10 años'), ('Más de 10 años', 'Más de 10 años')], null=True, verbose_name='Experiencia'),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='softwares',
            field=models.CharField(blank=True, choices=[('Adobe Indesign', 'Adobe Indesign'), ('SDL TRADOS Studio', 'SDL TRADOS Studio'), ('Wordfast (cat-tool)', 'Wordfast (cat-tool)'), ('Adobe Illustrator', 'Adobe Illustrator'), ('Adobe Photoshop', 'Adobe Photoshop'), ('AutoCAD', 'AutoCAD'), ('FrameMaker', 'FrameMaker'), ('Microsoft Excel', 'Microsoft Excel'), ('Passolo (cat-tool)', 'Passolo (cat-tool)'), ('Microsoft Powerpoint', 'Microsoft Powerpoint'), ('MemoQ', 'MemoQ')], max_length=250, null=True, verbose_name='Softwares'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='country',
            field=models.CharField(choices=[('Afganistán', 'Afganistán'), ('Albania', 'Albania'), ('Argelia', 'Argelia'), ('Andorra', 'Andorra'), ('Angola', 'Angola'), ('Arabia Saudí', 'Arabia Saudí'), ('Argentina', 'Argentina'), ('Armenia', 'Armenia'), ('Australia', 'Australia'), ('Austria', 'Austria'), ('Azerbaijan', 'Azerbaijan'), ('Bahamas', 'Bahamas'), ('Bahrain', 'Bahrain'), ('Bangladesh', 'Bangladesh'), ('Barbados', 'Barbados'), ('Bélgica', 'Bélgica'), ('Belize', 'Belize'), ('Benin', 'Benin'), ('Bermuda', 'Bermuda'), ('Bután', 'Bután'), ('Bolivia', 'Bolivia'), ('Bosnia & Herzegovina', 'Bosnia & Herzegovina'), ('Botswana', 'Botswana'), ('Brasil', 'Brasil'), ('Brunei', 'Brunei'), ('Bulgaria', 'Bulgaria'), ('Burundi', 'Burundi'), ('Cambodia', 'Cambodia'), ('Camerún', 'Camerún'), ('Canadá', 'Canadá'), ('Chad', 'Chad'), ('Chile', 'Chile'), ('China', 'China'), ('Colombia', 'Colombia'), ('Congo, República Democrática', 'Congo, República Democrática'), ('Costa Rica', 'Costa Rica'), ('Croacia', 'Croacia'), ('Cuba', 'Cuba'), ('Chipre', 'Chipre'), ('Dinamarca', 'Dinamarca'), ('Dominica', 'Dominica'), ('Ecuador', 'Ecuador'), ('Egipto', 'Egipto'), ('El Salvador', 'El Salvador'), ('Emigratos Árabes Unidos', 'Emigratos Árabes Unidos'), ('Estados Unidos', 'Estados Unidos'), ('Guinea Ecuatorial', 'Guinea Ecuatorial'), ('Eslovaquia', 'Eslovaquia'), ('España', 'España'), ('Estonia', 'Estonia'), ('Etiopia', 'Etiopia'), ('Fiji', 'Fiji'), ('Filipinas', 'Filipinas'), ('Finlandia', 'Finlandia'), ('Francia', 'Francia'), ('Gabon', 'Gabon'), ('Gambia', 'Gambia'), ('Georgia', 'Georgia'), ('Alemania', 'Alemania'), ('Ghana', 'Ghana'), ('Grecia', 'Grecia'), ('Guatemala', 'Guatemala'), ('Guinea', 'Guinea'), ('Guinea-Bissau', 'Guinea-Bissau'), ('Haití', 'Haití'), ('Holanda', 'Holanda'), ('Honduras', 'Honduras'), ('Hong Kong', 'Hong Kong'), ('Hungría', 'Hungría'), ('Islandia', 'Islandia'), ('India', 'India'), ('Indonesia', 'Indonesia'), ('Irán', 'Irán'), ('Irak', 'Irak'), ('Irlanda', 'Irlanda'), ('Israel', 'Israel'), ('Italia', 'Italia'), ('Jamaica', 'Jamaica'), ('Japón', 'Japón'), ('Jordania', 'Jordania'), ('Kazakhstan', 'Kazakhstan'), ('Kenya', 'Kenya'), ('Kiribati', 'Kiribati'), ('Corea del Norte', 'Corea del Norte'), ('Corea de Sur', 'Corea de Sur'), ('Kuwait', 'Kuwait'), ('Kyrgyzstan', 'Kyrgyzstan'), ('Laos', 'Laos'), ('Latvia', 'Latvia'), ('Letonia', 'Letonia'), ('Libia', 'Libia'), ('Liechtenstein', 'Liechtenstein'), ('Lituania', 'Lituania'), ('Luxemburgo', 'Luxemburgo'), ('Macedonia', 'Macedonia'), ('Madagascar', 'Madagascar'), ('Malawi', 'Malawi'), ('Malasia', 'Malasia'), ('Maldivas', 'Maldivas'), ('Mali', 'Mali'), ('Malta', 'Malta'), ('Islas Marshall', 'Islas Marshall'), ('Mauritania', 'Mauritania'), ('Mauricio', 'Mauricio'), ('México', 'México'), ('Micronesia', 'Micronesia'), ('Moldavia', 'Moldavia'), ('Mongolia', 'Mongolia'), ('Marruecos', 'Marruecos'), ('Mónaco', 'Mónaco'), ('Mozambique', 'Mozambique'), ('Namibia', 'Namibia'), ('Nauru', 'Nauru'), ('Nepal', 'Nepal'), ('Nueva Zelanda', 'Nueva Zelanda'), ('Nicaragua', 'Nicaragua'), ('Níger', 'Níger'), ('Nigeria', 'Nigeria'), ('Noruega', 'Noruega'), ('Omán', 'Omán'), ('Pakistán', 'Pakistán'), ('Panamá', 'Panamá'), ('Papua Nueva Guinea', 'Papua Nueva Guinea'), ('Paraguay', 'Paraguay'), ('Perú', 'Perú'), ('Polonia', 'Polonia'), ('Portugal', 'Portugal'), ('Qatar', 'Qatar'), ('Reino Unido', 'Reino Unido'), ('República Checa', 'República Checa'), ('República Dominicana', 'República Dominicana'), ('Rumania', 'Rumania'), ('Ruanda', 'Ruanda'), ('Rusia', 'Rusia'), ('Samoa', 'Samoa'), ('San Marino', 'San Marino'), ('Santo Tomé', 'Santo Tomé'), ('Senegal', 'Senegal'), ('Serbia & Montenegro', 'Serbia & Montenegro'), ('Seychelles', 'Seychelles'), ('Sierra Leona', 'Sierra Leona'), ('Singapur', 'Singapur'), ('Eslovenia', 'Eslovenia'), ('Salomón, Islas', 'Salomón, Islas'), ('Somalia', 'Somalia'), ('Sur África', 'Sur África'), ('Sri Lanka', 'Sri Lanka'), ('Sudan', 'Sudan'), ('Suecia', 'Suecia'), ('Suriname', 'Suriname'), ('Siria', 'Siria'), ('Suiza', 'Suiza'), ('Taiwán', 'Taiwán'), ('Tajikistan', 'Tajikistan'), ('Tanzania', 'Tanzania'), ('Tailandia', 'Tailandia'), ('Togo', 'Togo'), ('Tonga', 'Tonga'), ('Trinidad and Tobago', 'Trinidad and Tobago'), ('Túnez', 'Túnez'), ('Turquía', 'Turquía'), ('Turkmenistan', 'Turkmenistan'), ('Ucrania', 'Ucrania'), ('Uganda', 'Uganda'), ('Uruguay', 'Uruguay'), ('Uzbekistan', 'Uzbekistan'), ('Vanuatu', 'Vanuatu'), ('Venezuela', 'Venezuela'), ('Vietnam', 'Vietnam'), ('Yemen', 'Yemen'), ('Zambia', 'Zambia'), ('Zimbabwe', 'Zimbabwe'), ('Bielorrusia', 'Bielorrusia')], max_length=50, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='gender',
            field=models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer'), ('O', 'Otros')], default='Otros', max_length=9, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='province',
            field=models.CharField(choices=[('Álava', 'Álava'), ('Albacete', 'Albacete'), ('Alicante', 'Alicante'), ('Almería', 'Almería'), ('Asturias', 'Asturias'), ('Ávila', 'Ávila'), ('Badajoz', 'Badajoz'), ('Baleares', 'Baleares'), ('Barcelona', 'Barcelona'), ('Burgos', 'Burgos'), ('Cáceres', 'Cáceres'), ('Cádiz', 'Cádiz'), ('Cantabria', 'Cantabria'), ('Castellón', 'Castellón'), ('Ceuta', 'Ceuta'), ('Ciudad Real', 'Ciudad Real'), ('Córdoba', 'Córdoba'), ('Cuenca', 'Cuenca'), ('Gerona', 'Gerona'), ('Granada', 'Granada'), ('Guadalajara', 'Guadalajara'), ('Guipúzcoa', 'Guipúzcoa'), ('Huelva', 'Huelva'), ('Huesca', 'Huesca'), ('Jaén', 'Jaén'), ('La Coruña', 'La Coruña'), ('La Rioja', 'La Rioja'), ('Las Palmas', 'Las Palmas'), ('León', 'León'), ('Lerida', 'Lerida'), ('Lugo', 'Lugo'), ('Madrid', 'Madrid'), ('Málaga', 'Málaga'), ('Melilla', 'Melilla'), ('Murcia', 'Murcia'), ('Navarra', 'Navarra'), ('Orense', 'Orense'), ('Palencia', 'Palencia'), ('Pontevedra', 'Pontevedra'), ('Salamanca', 'Salamanca'), ('Santa Cruz de Tenerife', 'Santa Cruz de Tenerife'), ('Segovia', 'Segovia'), ('Sevilla', 'Sevilla'), ('Soria', 'Soria'), ('Tarragona', 'Tarragona'), ('Teruel', 'Teruel'), ('Toledo', 'Toledo'), ('Valencia', 'Valencia'), ('Valladolid', 'Valladolid'), ('Vizcaya', 'Vizcaya'), ('Zamora', 'Zamora'), ('Zaragoza', 'Zaragoza')], max_length=25, verbose_name='Provincia'),
        ),
    ]
