# Generated by Django 5.1.3 on 2024-11-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0005_alter_professionalprofile_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalprofile',
            name='experience',
            field=models.CharField(blank=True, choices=[('0', 'Sin experiencia'), ('<6m', 'Menos de 6 meses'), ('6m<1y', '6 meses - 1 año'), ('1y-2y', '1 - 2 años'), ('2y-5y', '2 - 5 años'), ('5y-10y', '5 - 10 años'), ('>10y', 'Más de 10 años')], max_length=10, null=True, verbose_name='Experiencia'),
        ),
    ]
