# Generated by Django 5.1.3 on 2024-11-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0009_alter_languagecombination_services_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='languagecombination',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='degree',
            field=models.CharField(blank=True, max_length=50, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='education',
            field=models.CharField(choices=[('ESO', 'ESO'), ('Bachillerato', 'Bachillerato'), ('FPI/Ciclo Formativo de Grado Medio', 'FPI/Ciclo Formativo de Grado Medio'), ('FPII/Ciclo Formativo de Grado Superior', 'FPII/Ciclo Formativo de Grado Superior'), ('Diplomatura', 'Diplomatura'), ('Licenciatura', 'Licenciatura'), ('Doctorado', 'Doctorado'), ('Cursos de Postgrado', 'Cursos de Postgrado'), ('Master', 'Master'), ('Otros', 'Otros')], default=0, max_length=40, verbose_name='Educación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='employment_status',
            field=models.CharField(choices=[('Autonomo', 'Autonomo'), ('Traductor ocasional', 'Traductor ocasional'), ('Estudiante', 'Estudiante'), ('Agencia', 'Agencia')], max_length=20, null=True, verbose_name='Situación Laboral'),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='experience',
            field=models.CharField(choices=[('0', 'Sin experiencia'), ('<6m', 'Menos de 6 meses'), ('6m<1y', '6 meses - 1 año'), ('1y-2y', '1 - 2 años'), ('2y-5y', '2 - 5 años'), ('5y-10y', '5 - 10 años'), ('>10y', 'Más de 10 años')], default=0, max_length=10, verbose_name='Experiencia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='native_languages',
            field=models.TextField(max_length=20, verbose_name='Lenguas Nativas'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='mobile_phone',
            field=models.CharField(blank=True, default=655555555, max_length=18, verbose_name='Nº Tlf Móvil'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='languagecombination',
            constraint=models.UniqueConstraint(fields=('translator', 'source_language', 'target_language'), name='unique_language_combination'),
        ),
    ]
