# Generated by Django 5.1.3 on 2024-11-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0010_alter_languagecombination_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalprofile',
            name='native_languages',
            field=models.TextField(default='', max_length=20, verbose_name='Lenguas Nativas'),
        ),
    ]
