# Generated by Django 5.1.3 on 2024-12-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0013_rename_curriculum_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='cv_file',
            field=models.FileField(upload_to='curriculum/', verbose_name='Currículum Vitae'),
        ),
        migrations.AlterField(
            model_name='files',
            name='voice_note',
            field=models.FileField(blank=True, null=True, upload_to='voice_note/', verbose_name='Nota de Voz'),
        ),
    ]
