# Generated by Django 5.1.4 on 2024-12-12 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0017_alter_translator_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translator',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.date(2000, 1, 1), null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='last_access',
            field=models.DateTimeField(blank=True, default=datetime.date(2000, 1, 1), null=True, verbose_name='Último acceso'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='registration_date',
            field=models.DateTimeField(blank=True, default=datetime.date(2000, 1, 1), null=True, verbose_name='Fecha de registro'),
        ),
    ]
