# Generated by Django 5.1.4 on 2024-12-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0018_alter_translator_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translator',
            name='postal_code',
            field=models.IntegerField(null=True, verbose_name='Código Postal'),
        ),
    ]
