# Generated by Django 5.1.4 on 2025-01-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0019_alter_translator_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translator',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
