# Generated by Django 5.1.4 on 2025-01-20 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0020_alter_translator_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagecombination',
            name='translator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languagecombinations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='translator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professionalprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
