# Generated by Django 5.1.4 on 2025-01-24 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0021_alter_languagecombination_translator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagecombination',
            name='translator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languagecombination', to=settings.AUTH_USER_MODEL),
        ),
    ]
