# Generated by Django 5.1.4 on 2025-02-14 15:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0023_alter_languagecombination_translator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='translator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL, verbose_name='Traductor'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='gender',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('O', 'Otros')], default='Otros', max_length=9, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='registration_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de registro'),
        ),
    ]
