# Generated by Django 5.1.4 on 2025-02-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0024_alter_files_translator_alter_translator_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagecombination',
            name='price_per_word',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Precio/pal. (€)'),
        ),
        migrations.AlterField(
            model_name='languagecombination',
            name='sworn_price_per_word',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Precio/pal. Jurada (€)'),
        ),
    ]
