# Generated by Django 5.2.5 on 2026-06-01 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0025_alter_languagecombination_price_per_word_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageCombinationApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de homologación')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Homologado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('language_combination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='translators.languagecombination', verbose_name='Combinación de idiomas')),
                ('superuser', models.ForeignKey(limit_choices_to={'is_superuser': True}, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by_me', to=settings.AUTH_USER_MODEL, verbose_name='Superusuario que homologa')),
                ('translator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_combinations', to=settings.AUTH_USER_MODEL, verbose_name='Traductor')),
            ],
            options={
                'verbose_name': 'Homologación de combinación',
                'verbose_name_plural': 'Homologaciones de combinaciones',
                'ordering': ['-approved_at'],
                'unique_together': {('superuser', 'translator', 'language_combination')},
            },
        ),
    ]
