# Generated by Django 5.1.4 on 2025-01-13 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0002_sqlquery_delete_savedquery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SQLQuery',
            new_name='SavedQuery',
        ),
    ]
