# Generated by Django 5.2.5 on 2025-08-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0004_alter_savedquery_name_alter_savedquery_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedquery',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
