import { jsxs as _jsxs, jsx as _jsx, Fragment as _Fragment } from "react/jsx-runtime";
import LinkButton from '../ui/LinkButton';
import { faFileAudio, faFilePdf, faList } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
const TranslatorProfile = ({ translator }) => {
    return (_jsxs(_Fragment, { children: [_jsxs("div", { className: "card mb-4 shadow-sm", children: [_jsxs("div", { className: "card-header bg-primary text-white", children: [_jsxs("h5", { className: "card-title mb-1", children: [translator.first_name, " ", translator.last_name] }), _jsx("h6", { className: "card-subtitle mb-0", children: translator.email })] }), _jsxs("div", { className: "card-body", children: [_jsx("div", { className: "row mb-3", children: _jsxs("div", { className: "col-md-12", children: [translator.files.cv_file && (_jsxs("a", { href: `${translator.files.cv_file}`, className: "btn btn-outline-primary me-2", children: [_jsx(FontAwesomeIcon, { icon: faFilePdf }), " Descargar CV"] })), translator.files.voice_note && (_jsxs("a", { href: `${translator.files.voice_note}`, className: "btn btn-outline-secondary", children: [_jsx(FontAwesomeIcon, { icon: faFileAudio }), " Escuchar Nota de Voz"] }))] }) }), _jsxs("div", { className: "row mb-3", children: [_jsx("div", { className: "col-md-6", children: _jsxs("p", { className: "card-text", children: [_jsx("strong", { children: "Direcci\u00F3n:" }), _jsx("br", {}), translator.address, ", ", translator.postal_code, ", ", translator.province, ", ", translator.country] }) }), _jsx("div", { className: "col-md-6", children: _jsxs("p", { className: "card-text", children: [_jsx("strong", { children: "Idiomas nativos:" }), _jsx("br", {}), translator.professional_profile.native_languages] }) })] }), _jsx("div", { className: "row mb-3", children: _jsx("div", { className: "col-md-6", children: _jsxs("p", { className: "card-text", children: [_jsx("strong", { children: "Genero:" }), _jsx("br", {}), translator.gender === 'H' ? 'Hombre' : translator.gender === 'M' ? 'Mujer' : 'Otro'] }) }) }), _jsxs("div", { className: "row mb-3", children: [_jsx("div", { className: "col-md-6", children: _jsxs("p", { className: "card-text", children: [_jsx("strong", { children: "Fecha de registro:" }), _jsx("br", {}), translator.registration_date
                                                    ? new Date(translator.registration_date).toLocaleDateString('es-ES', {
                                                        day: '2-digit',
                                                        month: '2-digit',
                                                        year: 'numeric',
                                                    })
                                                    : 'N/A'] }) }), _jsx("div", { className: "col-md-6", children: _jsxs("p", { className: "card-text", children: [_jsx("strong", { children: "\u00DAltimo acceso:" }), _jsx("br", {}), translator.last_access
                                                    ? new Date(translator.last_access).toLocaleDateString('es-ES', {
                                                        day: '2-digit',
                                                        month: '2-digit',
                                                        year: 'numeric',
                                                    })
                                                    : 'N/A'] }) })] }), _jsxs("div", { className: "row mb-3", children: [_jsx("div", { className: "col-md-6", children: _jsxs("p", { className: "card-text", children: [_jsx("strong", { children: "Educaci\u00F3n:" }), _jsx("br", {}), translator.professional_profile.education] }) }), _jsx("div", { className: "col-md-6", children: _jsxs("p", { className: "card-text", children: [_jsx("strong", { children: "Experiencia:" }), _jsx("br", {}), translator.professional_profile.experience] }) })] }), _jsx("div", { className: "row mb-3", children: _jsx("div", { className: "col-md-12", children: _jsxs("p", { className: "card-text", children: [_jsx("strong", { children: "Software:" }), _jsx("br", {}), translator.professional_profile.softwares] }) }) }), _jsx("div", { className: "row mt-5", children: translator.language_combination.map((combination) => (_jsx("div", { className: "col-md-6 mb-3", children: _jsxs("div", { className: "card h-100", children: [_jsx("div", { className: "card-header bg-body-secondary px-3 py-2 rounded-top", children: _jsxs("h6", { className: "card-subtitle mb-0", children: [_jsx("strong", { children: "De:" }), " ", combination.source_language, " ", _jsx("strong", { children: "A:" }), " ", combination.target_language] }) }), _jsxs("div", { className: "card-body", children: [_jsxs("p", { className: "card-text", children: [_jsx("strong", { children: "Servicios:" }), " ", combination.services] }), _jsxs("p", { className: "card-text", children: [_jsx("strong", { children: "Tipos de texto:" }), " ", combination.text_types] }), _jsxs("p", { className: "card-text", children: [_jsx("strong", { children: "Precio por palabra:" }), " ", combination.price_per_word, " \u20AC"] }), _jsxs("p", { className: "card-text", children: [_jsx("strong", { children: "Precio por palabra jurada:" }), " ", combination.sworn_price_per_word || 'No disponible', " \u20AC"] }), _jsxs("p", { className: "card-text", children: [_jsx("strong", { children: "Precio por hora:" }), " ", combination.price_per_hour || 'No disponible', " \u20AC"] })] })] }) }, combination.id))) })] })] }), _jsx("div", { className: "text-center", children: _jsx(LinkButton, { to: "/query_results", icon: faList, variant: "info", size: "lg", children: "Volver a resultados" }) })] }));
};
export default TranslatorProfile;
